package com.soft.blued.ui.feed.fragment;

import android.view.View;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.cardview.widget.CardView;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import butterknife.Unbinder;
import butterknife.internal.Utils;
import com.blued.android.framework.ui.custom.KeyboardListenLinearLayout;
import com.blued.android.framework.ui.custom.SwitchPanelRelativeLayout;
import com.blued.android.framework.view.shape.ShapeFrameLayout;
import com.blued.android.framework.view.shape.ShapeLinearLayout;
import com.blued.android.framework.view.shape.ShapeRelativeLayout;
import com.blued.android.framework.view.shape.ShapeTextView;
import com.blued.android.module.player.media.view.PLVideoPageView;
import com.scwang.smartrefresh.layout.SmartRefreshLayout;
import com.soft.blued.customview.AvatarLivingAnimView;
import com.soft.blued.customview.BannerADView;
import com.soft.blued.customview.CommonTopTitleNoTrans;
import com.soft.blued.customview.PhotoGridView;
import com.soft.blued.customview.TextViewFixTouchForDynamic;
import com.soft.blued.customview.consecutivescroller.ConsecutiveScrollerLayout;
import com.soft.blued.emoticon.ui.EmoticonsIndicatorView;
import com.soft.blued.emoticon.ui.EmoticonsPageView;
import com.soft.blued.emoticon.ui.EmoticonsToolBarView;
import com.soft.blued.ui.feed.view.FeedVoteGroup;
import com.soft.blued.ui.user.views.FollowStatusView;

public class FeedDetailsFragment_ViewBinding implements Unbinder {
  private FeedDetailsFragment b;
  
  public FeedDetailsFragment_ViewBinding(FeedDetailsFragment paramFeedDetailsFragment, View paramView) {
    this.b = paramFeedDetailsFragment;
    paramFeedDetailsFragment.topBar = Utils.a(paramView, 2131300293, "field 'topBar'");
    paramFeedDetailsFragment.topTitle = (CommonTopTitleNoTrans)Utils.a(paramView, 2131300300, "field 'topTitle'", CommonTopTitleNoTrans.class);
    paramFeedDetailsFragment.ivVisible = (ImageView)Utils.a(paramView, 2131297969, "field 'ivVisible'", ImageView.class);
    paramFeedDetailsFragment.tvVisible = (TextView)Utils.a(paramView, 2131301507, "field 'tvVisible'", TextView.class);
    paramFeedDetailsFragment.visibleMenuView = (ImageView)Utils.a(paramView, 2131301714, "field 'visibleMenuView'", ImageView.class);
    paramFeedDetailsFragment.imgPromotionBubble = (ImageView)Utils.a(paramView, 2131297543, "field 'imgPromotionBubble'", ImageView.class);
    paramFeedDetailsFragment.headerView = (ImageView)Utils.a(paramView, 2131297362, "field 'headerView'", ImageView.class);
    paramFeedDetailsFragment.imgLivingAnim = (AvatarLivingAnimView)Utils.a(paramView, 2131298685, "field 'imgLivingAnim'", AvatarLivingAnimView.class);
    paramFeedDetailsFragment.imgVerify = (ImageView)Utils.a(paramView, 2131297575, "field 'imgVerify'", ImageView.class);
    paramFeedDetailsFragment.nameView = (TextView)Utils.a(paramView, 2131299358, "field 'nameView'", TextView.class);
    paramFeedDetailsFragment.imgBluedMedal = (ImageView)Utils.a(paramView, 2131297447, "field 'imgBluedMedal'", ImageView.class);
    paramFeedDetailsFragment.tvFeedAd = (TextView)Utils.a(paramView, 2131300756, "field 'tvFeedAd'", TextView.class);
    paramFeedDetailsFragment.imgFeedAdArrow = (ImageView)Utils.a(paramView, 2131297481, "field 'imgFeedAdArrow'", ImageView.class);
    paramFeedDetailsFragment.llAdOption = (LinearLayout)Utils.a(paramView, 2131298695, "field 'llAdOption'", LinearLayout.class);
    paramFeedDetailsFragment.menuView = (ImageView)Utils.a(paramView, 2131299215, "field 'menuView'", ImageView.class);
    paramFeedDetailsFragment.followStatusView = (FollowStatusView)Utils.a(paramView, 2131297199, "field 'followStatusView'", FollowStatusView.class);
    paramFeedDetailsFragment.imgFeedSticky = (ImageView)Utils.a(paramView, 2131297482, "field 'imgFeedSticky'", ImageView.class);
    paramFeedDetailsFragment.tvReadNum = (TextView)Utils.a(paramView, 2131301233, "field 'tvReadNum'", TextView.class);
    paramFeedDetailsFragment.llRead = (ShapeLinearLayout)Utils.a(paramView, 2131299038, "field 'llRead'", ShapeLinearLayout.class);
    paramFeedDetailsFragment.ivReadExtend = (ImageView)Utils.a(paramView, 2131297908, "field 'ivReadExtend'", ImageView.class);
    paramFeedDetailsFragment.llReadNum = (LinearLayout)Utils.a(paramView, 2131299039, "field 'llReadNum'", LinearLayout.class);
    paramFeedDetailsFragment.tvFeedRecommendSource = (TextView)Utils.a(paramView, 2131300763, "field 'tvFeedRecommendSource'", TextView.class);
    paramFeedDetailsFragment.dotIconRecommend = (ShapeFrameLayout)Utils.a(paramView, 2131296958, "field 'dotIconRecommend'", ShapeFrameLayout.class);
    paramFeedDetailsFragment.distanceView = (TextView)Utils.a(paramView, 2131296943, "field 'distanceView'", TextView.class);
    paramFeedDetailsFragment.dotIconDistance = (ShapeFrameLayout)Utils.a(paramView, 2131296957, "field 'dotIconDistance'", ShapeFrameLayout.class);
    paramFeedDetailsFragment.timeView = (TextView)Utils.a(paramView, 2131300267, "field 'timeView'", TextView.class);
    paramFeedDetailsFragment.llDistanceAndTime = (LinearLayout)Utils.a(paramView, 2131298780, "field 'llDistanceAndTime'", LinearLayout.class);
    paramFeedDetailsFragment.tvSuperTopic = (TextView)Utils.a(paramView, 2131301364, "field 'tvSuperTopic'", TextView.class);
    paramFeedDetailsFragment.layoutSuperTopic = (ShapeLinearLayout)Utils.a(paramView, 2131298095, "field 'layoutSuperTopic'", ShapeLinearLayout.class);
    paramFeedDetailsFragment.sllSuperTopic = (ShapeLinearLayout)Utils.a(paramView, 2131299980, "field 'sllSuperTopic'", ShapeLinearLayout.class);
    paramFeedDetailsFragment.repostLayout = Utils.a(paramView, 2131299650, "field 'repostLayout'");
    paramFeedDetailsFragment.repostContentView = (TextViewFixTouchForDynamic)Utils.a(paramView, 2131299649, "field 'repostContentView'", TextViewFixTouchForDynamic.class);
    paramFeedDetailsFragment.contentView = (TextViewFixTouchForDynamic)Utils.a(paramView, 2131296838, "field 'contentView'", TextViewFixTouchForDynamic.class);
    paramFeedDetailsFragment.stvLongPicIcon = (ShapeTextView)Utils.a(paramView, 2131300102, "field 'stvLongPicIcon'", ShapeTextView.class);
    paramFeedDetailsFragment.imageOne = (ImageView)Utils.a(paramView, 2131297414, "field 'imageOne'", ImageView.class);
    paramFeedDetailsFragment.cvImageOne = (CardView)Utils.a(paramView, 2131296891, "field 'cvImageOne'", CardView.class);
    paramFeedDetailsFragment.imageTwoFour = (PhotoGridView)Utils.a(paramView, 2131297416, "field 'imageTwoFour'", PhotoGridView.class);
    paramFeedDetailsFragment.imageOther = (PhotoGridView)Utils.a(paramView, 2131297415, "field 'imageOther'", PhotoGridView.class);
    paramFeedDetailsFragment.videoView = (PLVideoPageView)Utils.a(paramView, 2131301607, "field 'videoView'", PLVideoPageView.class);
    paramFeedDetailsFragment.cardVideo = (CardView)Utils.a(paramView, 2131296658, "field 'cardVideo'", CardView.class);
    paramFeedDetailsFragment.imgWebShare = (ImageView)Utils.a(paramView, 2131297586, "field 'imgWebShare'", ImageView.class);
    paramFeedDetailsFragment.tvWebShareContent = (TextView)Utils.a(paramView, 2131301524, "field 'tvWebShareContent'", TextView.class);
    paramFeedDetailsFragment.tvWebShareTitleRight = (TextView)Utils.a(paramView, 2131301526, "field 'tvWebShareTitleRight'", TextView.class);
    paramFeedDetailsFragment.tvWebShareDesc = (TextView)Utils.a(paramView, 2131301525, "field 'tvWebShareDesc'", TextView.class);
    paramFeedDetailsFragment.cvWebShare = (CardView)Utils.a(paramView, 2131296902, "field 'cvWebShare'", CardView.class);
    paramFeedDetailsFragment.feedVote = (FeedVoteGroup)Utils.a(paramView, 2131297051, "field 'feedVote'", FeedVoteGroup.class);
    paramFeedDetailsFragment.cardVote = (CardView)Utils.a(paramView, 2131296661, "field 'cardVote'", CardView.class);
    paramFeedDetailsFragment.llContentAll = (ShapeLinearLayout)Utils.a(paramView, 2131298759, "field 'llContentAll'", ShapeLinearLayout.class);
    paramFeedDetailsFragment.feedInfo = (LinearLayout)Utils.a(paramView, 2131297040, "field 'feedInfo'", LinearLayout.class);
    paramFeedDetailsFragment.locationIcon = (ImageView)Utils.a(paramView, 2131299161, "field 'locationIcon'", ImageView.class);
    paramFeedDetailsFragment.locationText = (TextView)Utils.a(paramView, 2131299163, "field 'locationText'", TextView.class);
    paramFeedDetailsFragment.locationLayout = (ShapeLinearLayout)Utils.a(paramView, 2131299162, "field 'locationLayout'", ShapeLinearLayout.class);
    paramFeedDetailsFragment.voteText = (TextView)Utils.a(paramView, 2131301720, "field 'voteText'", TextView.class);
    paramFeedDetailsFragment.voteNumLayout = (ShapeLinearLayout)Utils.a(paramView, 2131301719, "field 'voteNumLayout'", ShapeLinearLayout.class);
    paramFeedDetailsFragment.zanText = (TextView)Utils.a(paramView, 2131301788, "field 'zanText'", TextView.class);
    paramFeedDetailsFragment.zanNumText = (TextView)Utils.a(paramView, 2131301787, "field 'zanNumText'", TextView.class);
    paramFeedDetailsFragment.llLike = (ShapeLinearLayout)Utils.a(paramView, 2131298911, "field 'llLike'", ShapeLinearLayout.class);
    paramFeedDetailsFragment.commentText = (TextView)Utils.a(paramView, 2131296802, "field 'commentText'", TextView.class);
    paramFeedDetailsFragment.commentNumText = (TextView)Utils.a(paramView, 2131296800, "field 'commentNumText'", TextView.class);
    paramFeedDetailsFragment.llComment = (ShapeLinearLayout)Utils.a(paramView, 2131298753, "field 'llComment'", ShapeLinearLayout.class);
    paramFeedDetailsFragment.repostText = (TextView)Utils.a(paramView, 2131299652, "field 'repostText'", TextView.class);
    paramFeedDetailsFragment.repostNumText = (TextView)Utils.a(paramView, 2131299651, "field 'repostNumText'", TextView.class);
    paramFeedDetailsFragment.llRepost = (ShapeLinearLayout)Utils.a(paramView, 2131299055, "field 'llRepost'", ShapeLinearLayout.class);
    paramFeedDetailsFragment.llTab = (ShapeLinearLayout)Utils.a(paramView, 2131299091, "field 'llTab'", ShapeLinearLayout.class);
    paramFeedDetailsFragment.feed = (ConstraintLayout)Utils.a(paramView, 2131297032, "field 'feed'", ConstraintLayout.class);
    paramFeedDetailsFragment.recyclerView = (RecyclerView)Utils.a(paramView, 2131299605, "field 'recyclerView'", RecyclerView.class);
    paramFeedDetailsFragment.rvFeed = (RecyclerView)Utils.a(paramView, 2131299771, "field 'rvFeed'", RecyclerView.class);
    paramFeedDetailsFragment.refreshLayout = (SmartRefreshLayout)Utils.a(paramView, 2131299616, "field 'refreshLayout'", SmartRefreshLayout.class);
    paramFeedDetailsFragment.keyboardView = Utils.a(paramView, 2131297985, "field 'keyboardView'");
    paramFeedDetailsFragment.editView = (EditText)Utils.a(paramView, 2131296971, "field 'editView'", EditText.class);
    paramFeedDetailsFragment.editLayout = (ShapeRelativeLayout)Utils.a(paramView, 2131296968, "field 'editLayout'", ShapeRelativeLayout.class);
    paramFeedDetailsFragment.iconLike = (ImageView)Utils.a(paramView, 2131297400, "field 'iconLike'", ImageView.class);
    paramFeedDetailsFragment.feedLike = (ShapeRelativeLayout)Utils.a(paramView, 2131297042, "field 'feedLike'", ShapeRelativeLayout.class);
    paramFeedDetailsFragment.iconShare = (ImageView)Utils.a(paramView, 2131297405, "field 'iconShare'", ImageView.class);
    paramFeedDetailsFragment.llDetailsShare = (ShapeRelativeLayout)Utils.a(paramView, 2131298774, "field 'llDetailsShare'", ShapeRelativeLayout.class);
    paramFeedDetailsFragment.layoutLikeShare = (LinearLayout)Utils.a(paramView, 2131298069, "field 'layoutLikeShare'", LinearLayout.class);
    paramFeedDetailsFragment.expressionBtn = (ImageView)Utils.a(paramView, 2131297025, "field 'expressionBtn'", ImageView.class);
    paramFeedDetailsFragment.sendBtn = (ShapeTextView)Utils.a(paramView, 2131299890, "field 'sendBtn'", ShapeTextView.class);
    paramFeedDetailsFragment.layoutComment = (LinearLayout)Utils.a(paramView, 2131298051, "field 'layoutComment'", LinearLayout.class);
    paramFeedDetailsFragment.inputLayoutUp = (LinearLayout)Utils.a(paramView, 2131297596, "field 'inputLayoutUp'", LinearLayout.class);
    paramFeedDetailsFragment.viewEpv = (EmoticonsPageView)Utils.a(paramView, 2131301643, "field 'viewEpv'", EmoticonsPageView.class);
    paramFeedDetailsFragment.viewEiv = (EmoticonsIndicatorView)Utils.a(paramView, 2131301642, "field 'viewEiv'", EmoticonsIndicatorView.class);
    paramFeedDetailsFragment.line = (TextView)Utils.a(paramView, 2131298118, "field 'line'", TextView.class);
    paramFeedDetailsFragment.viewEtv = (EmoticonsToolBarView)Utils.a(paramView, 2131301644, "field 'viewEtv'", EmoticonsToolBarView.class);
    paramFeedDetailsFragment.emoticonLayout = (LinearLayout)Utils.a(paramView, 2131296983, "field 'emoticonLayout'", LinearLayout.class);
    paramFeedDetailsFragment.emoticonLayoutRoot = (SwitchPanelRelativeLayout)Utils.a(paramView, 2131296984, "field 'emoticonLayoutRoot'", SwitchPanelRelativeLayout.class);
    paramFeedDetailsFragment.keyboardRelativeLayout = (KeyboardListenLinearLayout)Utils.a(paramView, 2131297981, "field 'keyboardRelativeLayout'", KeyboardListenLinearLayout.class);
    paramFeedDetailsFragment.feedVisible = (ConstraintLayout)Utils.a(paramView, 2131297050, "field 'feedVisible'", ConstraintLayout.class);
    paramFeedDetailsFragment.feedUserInfo = (ConstraintLayout)Utils.a(paramView, 2131297049, "field 'feedUserInfo'", ConstraintLayout.class);
    paramFeedDetailsFragment.feedLocation = (LinearLayout)Utils.a(paramView, 2131297043, "field 'feedLocation'", LinearLayout.class);
    paramFeedDetailsFragment.viewTopicCorner = Utils.a(paramView, 2131301689, "field 'viewTopicCorner'");
    paramFeedDetailsFragment.viewCircleCorner = Utils.a(paramView, 2131301632, "field 'viewCircleCorner'");
    paramFeedDetailsFragment.llRefresh = (LinearLayout)Utils.a(paramView, 2131299045, "field 'llRefresh'", LinearLayout.class);
    paramFeedDetailsFragment.llNoData = (LinearLayout)Utils.a(paramView, 2131298982, "field 'llNoData'", LinearLayout.class);
    paramFeedDetailsFragment.ivNoData = (ImageView)Utils.a(paramView, 2131297878, "field 'ivNoData'", ImageView.class);
    paramFeedDetailsFragment.tvNoData = (TextView)Utils.a(paramView, 2131301108, "field 'tvNoData'", TextView.class);
    paramFeedDetailsFragment.llMore = (LinearLayout)Utils.a(paramView, 2131298956, "field 'llMore'", LinearLayout.class);
    paramFeedDetailsFragment.llMoreComment = (LinearLayout)Utils.a(paramView, 2131298957, "field 'llMoreComment'", LinearLayout.class);
    paramFeedDetailsFragment.bannerLine = Utils.a(paramView, 2131296496, "field 'bannerLine'");
    paramFeedDetailsFragment.bannerAD = (BannerADView)Utils.a(paramView, 2131296495, "field 'bannerAD'", BannerADView.class);
    paramFeedDetailsFragment.recommendLine = Utils.a(paramView, 2131299585, "field 'recommendLine'");
    paramFeedDetailsFragment.tvRecommend = (TextView)Utils.a(paramView, 2131301238, "field 'tvRecommend'", TextView.class);
    paramFeedDetailsFragment.llRecommendMore = (LinearLayout)Utils.a(paramView, 2131299043, "field 'llRecommendMore'", LinearLayout.class);
    paramFeedDetailsFragment.dynamicSkin = (ImageView)Utils.a(paramView, 2131297038, "field 'dynamicSkin'", ImageView.class);
    paramFeedDetailsFragment.avatarWidget = (ImageView)Utils.a(paramView, 2131297700, "field 'avatarWidget'", ImageView.class);
    paramFeedDetailsFragment.svHeader = (ScrollView)Utils.a(paramView, 2131300145, "field 'svHeader'", ScrollView.class);
    paramFeedDetailsFragment.cslView = (ConsecutiveScrollerLayout)Utils.a(paramView, 2131296854, "field 'cslView'", ConsecutiveScrollerLayout.class);
  }
  
  public void unbind() {
    FeedDetailsFragment feedDetailsFragment = this.b;
    if (feedDetailsFragment != null) {
      this.b = null;
      feedDetailsFragment.topBar = null;
      feedDetailsFragment.topTitle = null;
      feedDetailsFragment.ivVisible = null;
      feedDetailsFragment.tvVisible = null;
      feedDetailsFragment.visibleMenuView = null;
      feedDetailsFragment.imgPromotionBubble = null;
      feedDetailsFragment.headerView = null;
      feedDetailsFragment.imgLivingAnim = null;
      feedDetailsFragment.imgVerify = null;
      feedDetailsFragment.nameView = null;
      feedDetailsFragment.imgBluedMedal = null;
      feedDetailsFragment.tvFeedAd = null;
      feedDetailsFragment.imgFeedAdArrow = null;
      feedDetailsFragment.llAdOption = null;
      feedDetailsFragment.menuView = null;
      feedDetailsFragment.followStatusView = null;
      feedDetailsFragment.imgFeedSticky = null;
      feedDetailsFragment.tvReadNum = null;
      feedDetailsFragment.llRead = null;
      feedDetailsFragment.ivReadExtend = null;
      feedDetailsFragment.llReadNum = null;
      feedDetailsFragment.tvFeedRecommendSource = null;
      feedDetailsFragment.dotIconRecommend = null;
      feedDetailsFragment.distanceView = null;
      feedDetailsFragment.dotIconDistance = null;
      feedDetailsFragment.timeView = null;
      feedDetailsFragment.llDistanceAndTime = null;
      feedDetailsFragment.tvSuperTopic = null;
      feedDetailsFragment.layoutSuperTopic = null;
      feedDetailsFragment.sllSuperTopic = null;
      feedDetailsFragment.repostLayout = null;
      feedDetailsFragment.repostContentView = null;
      feedDetailsFragment.contentView = null;
      feedDetailsFragment.stvLongPicIcon = null;
      feedDetailsFragment.imageOne = null;
      feedDetailsFragment.cvImageOne = null;
      feedDetailsFragment.imageTwoFour = null;
      feedDetailsFragment.imageOther = null;
      feedDetailsFragment.videoView = null;
      feedDetailsFragment.cardVideo = null;
      feedDetailsFragment.imgWebShare = null;
      feedDetailsFragment.tvWebShareContent = null;
      feedDetailsFragment.tvWebShareTitleRight = null;
      feedDetailsFragment.tvWebShareDesc = null;
      feedDetailsFragment.cvWebShare = null;
      feedDetailsFragment.feedVote = null;
      feedDetailsFragment.cardVote = null;
      feedDetailsFragment.llContentAll = null;
      feedDetailsFragment.feedInfo = null;
      feedDetailsFragment.locationIcon = null;
      feedDetailsFragment.locationText = null;
      feedDetailsFragment.locationLayout = null;
      feedDetailsFragment.voteText = null;
      feedDetailsFragment.voteNumLayout = null;
      feedDetailsFragment.zanText = null;
      feedDetailsFragment.zanNumText = null;
      feedDetailsFragment.llLike = null;
      feedDetailsFragment.commentText = null;
      feedDetailsFragment.commentNumText = null;
      feedDetailsFragment.llComment = null;
      feedDetailsFragment.repostText = null;
      feedDetailsFragment.repostNumText = null;
      feedDetailsFragment.llRepost = null;
      feedDetailsFragment.llTab = null;
      feedDetailsFragment.feed = null;
      feedDetailsFragment.recyclerView = null;
      feedDetailsFragment.rvFeed = null;
      feedDetailsFragment.refreshLayout = null;
      feedDetailsFragment.keyboardView = null;
      feedDetailsFragment.editView = null;
      feedDetailsFragment.editLayout = null;
      feedDetailsFragment.iconLike = null;
      feedDetailsFragment.feedLike = null;
      feedDetailsFragment.iconShare = null;
      feedDetailsFragment.llDetailsShare = null;
      feedDetailsFragment.layoutLikeShare = null;
      feedDetailsFragment.expressionBtn = null;
      feedDetailsFragment.sendBtn = null;
      feedDetailsFragment.layoutComment = null;
      feedDetailsFragment.inputLayoutUp = null;
      feedDetailsFragment.viewEpv = null;
      feedDetailsFragment.viewEiv = null;
      feedDetailsFragment.line = null;
      feedDetailsFragment.viewEtv = null;
      feedDetailsFragment.emoticonLayout = null;
      feedDetailsFragment.emoticonLayoutRoot = null;
      feedDetailsFragment.keyboardRelativeLayout = null;
      feedDetailsFragment.feedVisible = null;
      feedDetailsFragment.feedUserInfo = null;
      feedDetailsFragment.feedLocation = null;
      feedDetailsFragment.viewTopicCorner = null;
      feedDetailsFragment.viewCircleCorner = null;
      feedDetailsFragment.llRefresh = null;
      feedDetailsFragment.llNoData = null;
      feedDetailsFragment.ivNoData = null;
      feedDetailsFragment.tvNoData = null;
      feedDetailsFragment.llMore = null;
      feedDetailsFragment.llMoreComment = null;
      feedDetailsFragment.bannerLine = null;
      feedDetailsFragment.bannerAD = null;
      feedDetailsFragment.recommendLine = null;
      feedDetailsFragment.tvRecommend = null;
      feedDetailsFragment.llRecommendMore = null;
      feedDetailsFragment.dynamicSkin = null;
      feedDetailsFragment.avatarWidget = null;
      feedDetailsFragment.svHeader = null;
      feedDetailsFragment.cslView = null;
      return;
    } 
    throw new IllegalStateException("Bindings already cleared.");
  }
}


/* Location:              D:\code\BluedHook\classes.dex\com.soft.blued9136188-dex2jar.jar!\com\soft\blue\\ui\feed\fragment\FeedDetailsFragment_ViewBinding.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */