package com.qiniu.pili.droid.streaming;

public enum AVCodecType {
  HW_AUDIO_CODEC, HW_VIDEO_CODEC, HW_VIDEO_SURFACE_AS_INPUT_WITH_HW_AUDIO_CODEC, HW_VIDEO_SURFACE_AS_INPUT_WITH_SW_AUDIO_CODEC, HW_VIDEO_WITH_HW_AUDIO_CODEC, HW_VIDEO_YUV_AS_INPUT_WITH_HW_AUDIO_CODEC, SW_AUDIO_CODEC, SW_VIDEO_CODEC, SW_VIDEO_WITH_HW_AUDIO_CODEC, SW_VIDEO_WITH_SW_AUDIO_CODEC;
  
  static {
    SW_AUDIO_CODEC = new AVCodecType("SW_AUDIO_CODEC", 3);
    HW_AUDIO_CODEC = new AVCodecType("HW_AUDIO_CODEC", 4);
    SW_VIDEO_CODEC = new AVCodecType("SW_VIDEO_CODEC", 5);
    HW_VIDEO_CODEC = new AVCodecType("HW_VIDEO_CODEC", 6);
    HW_VIDEO_SURFACE_AS_INPUT_WITH_HW_AUDIO_CODEC = new AVCodecType("HW_VIDEO_SURFACE_AS_INPUT_WITH_HW_AUDIO_CODEC", 7);
    HW_VIDEO_YUV_AS_INPUT_WITH_HW_AUDIO_CODEC = new AVCodecType("HW_VIDEO_YUV_AS_INPUT_WITH_HW_AUDIO_CODEC", 8);
    AVCodecType aVCodecType = new AVCodecType("HW_VIDEO_SURFACE_AS_INPUT_WITH_SW_AUDIO_CODEC", 9);
    HW_VIDEO_SURFACE_AS_INPUT_WITH_SW_AUDIO_CODEC = aVCodecType;
    $VALUES = new AVCodecType[] { HW_VIDEO_WITH_HW_AUDIO_CODEC, SW_VIDEO_WITH_HW_AUDIO_CODEC, SW_VIDEO_WITH_SW_AUDIO_CODEC, SW_AUDIO_CODEC, HW_AUDIO_CODEC, SW_VIDEO_CODEC, HW_VIDEO_CODEC, HW_VIDEO_SURFACE_AS_INPUT_WITH_HW_AUDIO_CODEC, HW_VIDEO_YUV_AS_INPUT_WITH_HW_AUDIO_CODEC, aVCodecType };
  }
}


/* Location:              D:\code\BluedHook\classes.dex\com.soft.blued9136188-dex2jar.jar!\com\qiniu\pili\droid\streaming\AVCodecType.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */