package com.blued.android.module.external_sense_library.config;

public interface BluedBeautifyKey {
  public enum KEY implements BluedBeautifyKey {
    ST_BEAUTIFY_3D_APPLE_MUSLE_RATIO,
    ST_BEAUTIFY_3D_BRIGHT_EYE_RATIO,
    ST_BEAUTIFY_3D_CHIN_LENGTH_RATIO,
    ST_BEAUTIFY_3D_EYE_ANGLE_RATIO,
    ST_BEAUTIFY_3D_EYE_DISTANCE_RATIO,
    ST_BEAUTIFY_3D_HAIRLINE_HEIGHT_RATIO,
    ST_BEAUTIFY_3D_MOUTH_SIZE_RATIO,
    ST_BEAUTIFY_3D_NARROW_NOSE_RATIO,
    ST_BEAUTIFY_3D_NOSE_LENGTH_RATIO,
    ST_BEAUTIFY_3D_OPEN_CANTHUS_RATIO,
    ST_BEAUTIFY_3D_PHILTRUM_LENGTH_RATIO,
    ST_BEAUTIFY_3D_PROFILE_RHINOPLASTY_RATIO,
    ST_BEAUTIFY_3D_REMOVE_DARK_CIRCLES_RATIO,
    ST_BEAUTIFY_3D_REMOVE_NASOLABIAL_FOLDS_RATIO,
    ST_BEAUTIFY_3D_THIN_FACE_SHAPE_RATIO,
    ST_BEAUTIFY_3D_WHITE_TEETH_RATIO,
    ST_BEAUTIFY_CONSTRACT_STRENGTH,
    ST_BEAUTIFY_DEHIGHLIGHT_STRENGTH,
    ST_BEAUTIFY_ENLARGE_EYE_RATIO,
    ST_BEAUTIFY_NARROW_FACE_STRENGTH,
    ST_BEAUTIFY_REDDEN_STRENGTH,
    ST_BEAUTIFY_ROUND_EYE_RATIO,
    ST_BEAUTIFY_SATURATION_STRENGTH,
    ST_BEAUTIFY_SHRINK_FACE_RATIO,
    ST_BEAUTIFY_SHRINK_JAW_RATIO,
    ST_BEAUTIFY_SMOOTH_STRENGTH,
    ST_BEAUTIFY_WHITEN_STRENGTH(0, 4);
    
    private int index;
    
    private int stBeautyParamsType;
    
    static {
      ST_BEAUTIFY_DEHIGHLIGHT_STRENGTH = new KEY("ST_BEAUTIFY_DEHIGHLIGHT_STRENGTH", 3, 3, 10);
      ST_BEAUTIFY_SHRINK_FACE_RATIO = new KEY("ST_BEAUTIFY_SHRINK_FACE_RATIO", 4, 4, 6);
      ST_BEAUTIFY_ENLARGE_EYE_RATIO = new KEY("ST_BEAUTIFY_ENLARGE_EYE_RATIO", 5, 5, 5);
      ST_BEAUTIFY_SHRINK_JAW_RATIO = new KEY("ST_BEAUTIFY_SHRINK_JAW_RATIO", 6, 6, 7);
      ST_BEAUTIFY_NARROW_FACE_STRENGTH = new KEY("ST_BEAUTIFY_NARROW_FACE_STRENGTH", 7, 7, 11);
      ST_BEAUTIFY_CONSTRACT_STRENGTH = new KEY("ST_BEAUTIFY_CONSTRACT_STRENGTH", 8, 8, 8);
      ST_BEAUTIFY_SATURATION_STRENGTH = new KEY("ST_BEAUTIFY_SATURATION_STRENGTH", 9, 9, 9);
      ST_BEAUTIFY_ROUND_EYE_RATIO = new KEY("ST_BEAUTIFY_ROUND_EYE_RATIO", 10, 10, 35);
      ST_BEAUTIFY_3D_NARROW_NOSE_RATIO = new KEY("ST_BEAUTIFY_3D_NARROW_NOSE_RATIO", 11, 11, 35);
      ST_BEAUTIFY_3D_NOSE_LENGTH_RATIO = new KEY("ST_BEAUTIFY_3D_NOSE_LENGTH_RATIO", 12, 12, 35);
      ST_BEAUTIFY_3D_CHIN_LENGTH_RATIO = new KEY("ST_BEAUTIFY_3D_CHIN_LENGTH_RATIO", 13, 13, 35);
      ST_BEAUTIFY_3D_MOUTH_SIZE_RATIO = new KEY("ST_BEAUTIFY_3D_MOUTH_SIZE_RATIO", 14, 14, 35);
      ST_BEAUTIFY_3D_PHILTRUM_LENGTH_RATIO = new KEY("ST_BEAUTIFY_3D_PHILTRUM_LENGTH_RATIO", 15, 15, 35);
      ST_BEAUTIFY_3D_HAIRLINE_HEIGHT_RATIO = new KEY("ST_BEAUTIFY_3D_HAIRLINE_HEIGHT_RATIO", 16, 16, 35);
      ST_BEAUTIFY_3D_THIN_FACE_SHAPE_RATIO = new KEY("ST_BEAUTIFY_3D_THIN_FACE_SHAPE_RATIO", 17, 17, 35);
      ST_BEAUTIFY_3D_EYE_DISTANCE_RATIO = new KEY("ST_BEAUTIFY_3D_EYE_DISTANCE_RATIO", 18, 18, 35);
      ST_BEAUTIFY_3D_EYE_ANGLE_RATIO = new KEY("ST_BEAUTIFY_3D_EYE_ANGLE_RATIO", 19, 19, 35);
      ST_BEAUTIFY_3D_OPEN_CANTHUS_RATIO = new KEY("ST_BEAUTIFY_3D_OPEN_CANTHUS_RATIO", 20, 20, 35);
      ST_BEAUTIFY_3D_PROFILE_RHINOPLASTY_RATIO = new KEY("ST_BEAUTIFY_3D_PROFILE_RHINOPLASTY_RATIO", 21, 21, 35);
      ST_BEAUTIFY_3D_BRIGHT_EYE_RATIO = new KEY("ST_BEAUTIFY_3D_BRIGHT_EYE_RATIO", 22, 22, 35);
      ST_BEAUTIFY_3D_REMOVE_DARK_CIRCLES_RATIO = new KEY("ST_BEAUTIFY_3D_REMOVE_DARK_CIRCLES_RATIO", 23, 23, 35);
      ST_BEAUTIFY_3D_REMOVE_NASOLABIAL_FOLDS_RATIO = new KEY("ST_BEAUTIFY_3D_REMOVE_NASOLABIAL_FOLDS_RATIO", 24, 24, 35);
      ST_BEAUTIFY_3D_WHITE_TEETH_RATIO = new KEY("ST_BEAUTIFY_3D_WHITE_TEETH_RATIO", 25, 25, 35);
      ST_BEAUTIFY_3D_APPLE_MUSLE_RATIO = new KEY("ST_BEAUTIFY_3D_APPLE_MUSLE_RATIO", 26, 26, 35);
      $VALUES = new KEY[] { 
          ST_BEAUTIFY_WHITEN_STRENGTH, ST_BEAUTIFY_REDDEN_STRENGTH, ST_BEAUTIFY_SMOOTH_STRENGTH, ST_BEAUTIFY_DEHIGHLIGHT_STRENGTH, ST_BEAUTIFY_SHRINK_FACE_RATIO, ST_BEAUTIFY_ENLARGE_EYE_RATIO, ST_BEAUTIFY_SHRINK_JAW_RATIO, ST_BEAUTIFY_NARROW_FACE_STRENGTH, ST_BEAUTIFY_CONSTRACT_STRENGTH, ST_BEAUTIFY_SATURATION_STRENGTH, 
          ST_BEAUTIFY_ROUND_EYE_RATIO, ST_BEAUTIFY_3D_NARROW_NOSE_RATIO, ST_BEAUTIFY_3D_NOSE_LENGTH_RATIO, ST_BEAUTIFY_3D_CHIN_LENGTH_RATIO, ST_BEAUTIFY_3D_MOUTH_SIZE_RATIO, ST_BEAUTIFY_3D_PHILTRUM_LENGTH_RATIO, ST_BEAUTIFY_3D_HAIRLINE_HEIGHT_RATIO, ST_BEAUTIFY_3D_THIN_FACE_SHAPE_RATIO, ST_BEAUTIFY_3D_EYE_DISTANCE_RATIO, ST_BEAUTIFY_3D_EYE_ANGLE_RATIO, 
          ST_BEAUTIFY_3D_OPEN_CANTHUS_RATIO, ST_BEAUTIFY_3D_PROFILE_RHINOPLASTY_RATIO, ST_BEAUTIFY_3D_BRIGHT_EYE_RATIO, ST_BEAUTIFY_3D_REMOVE_DARK_CIRCLES_RATIO, ST_BEAUTIFY_3D_REMOVE_NASOLABIAL_FOLDS_RATIO, ST_BEAUTIFY_3D_WHITE_TEETH_RATIO, ST_BEAUTIFY_3D_APPLE_MUSLE_RATIO };
    }
    
    KEY(int param1Int1, int param1Int2) {
      this.index = param1Int1;
      this.stBeautyParamsType = param1Int2;
    }
    
    public int getBeautyParamsType() {
      return this.stBeautyParamsType;
    }
    
    public int getIndex() {
      return this.index;
    }
  }
}


/* Location:              D:\code\BluedHook\classes.dex\com.soft.blued5032032-dex2jar.jar!\com\blued\android\module\external_sense_library\config\BluedBeautifyKey.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */